version: '3'
services:
  #######################################
  # PHP application Docker container
  #######################################
  app:
    image: actency/docker-apache-php:5.3
    links:
      - memcached
    ports:
      - "8080:80"
      - "9000:9000"
    environment:
      - SERVERNAME=localhost
      - SERVERALIAS=localhost.dev
      - DRUSH_VERSION = 8 / 9
      - DOCUMENTROOT=htdocs
    volumes:
      - ./src/:/var/www/html/htdocs/
      - ./statics/:/var/www/html/statics/
      - ./vhosts/123doc.local:/etc/apache2/sites-enabled/123doc.local

  #######################################
  # Memcached
  #######################################
  memcached:
    image: memcached:alpine
    ports:
     - "11211:11211"
